package com.explapp.carsgamelegacy;
import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.*;import android.view.*;import android.widget.*;import java.util.*;

public final class MainActivity extends Activity{
 SharedPreferences prefs;RaceView race;TextView scoreView,status;Button pause;int best;
 public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("race_v2",0);best=prefs.getInt("best",0);showMenu();}
 void showMenu(){LinearLayout root=panel();TextView t=text("سباق الطريق",32,true);root.addView(t);TextView info=text("بدّل المسار وتجنب السيارات\nأفضل نتيجة: "+best,19,false);root.addView(info);RaceView preview=new RaceView(this);preview.demo=true;root.addView(preview,new LinearLayout.LayoutParams(-1,dp(210)));Button start=button("ابدأ السباق",0xff1687c3);start.setOnClickListener(new View.OnClickListener(){public void onClick(View v){startRace();}});root.addView(start);setContentView(root);}
 void startRace(){FrameLayout frame=new FrameLayout(this);race=new RaceView(this);frame.addView(race,new FrameLayout.LayoutParams(-1,-1));LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER);top.setPadding(dp(8),dp(5),dp(8),dp(5));top.setBackgroundColor(0xaa10253a);scoreView=text("النقاط: 0  |  الأفضل: "+best,17,true);scoreView.setTextColor(Color.WHITE);top.addView(scoreView,new LinearLayout.LayoutParams(0,dp(48),1));pause=button("إيقاف مؤقت",0xff607d8b);pause.setOnClickListener(new View.OnClickListener(){public void onClick(View v){race.togglePause();pause.setText(race.paused?"متابعة":"إيقاف مؤقت");}});top.addView(pause,new LinearLayout.LayoutParams(dp(140),dp(48)));frame.addView(top,new FrameLayout.LayoutParams(-1,dp(58),Gravity.TOP));
 LinearLayout controls=new LinearLayout(this);controls.setGravity(Gravity.CENTER);controls.setPadding(dp(12),dp(8),dp(12),dp(8));controls.setBackgroundColor(0xaa10253a);Button right=button("يمين",0xff246ba0);right.setOnClickListener(new View.OnClickListener(){public void onClick(View v){race.move(1);}});Button left=button("يسار",0xff246ba0);left.setOnClickListener(new View.OnClickListener(){public void onClick(View v){race.move(-1);}});controls.addView(right,new LinearLayout.LayoutParams(0,dp(58),1));controls.addView(new View(this),new LinearLayout.LayoutParams(dp(12),1));controls.addView(left,new LinearLayout.LayoutParams(0,dp(58),1));frame.addView(controls,new FrameLayout.LayoutParams(-1,dp(76),Gravity.BOTTOM));setContentView(frame);race.start();}
 void updateScore(int score){if(scoreView!=null)scoreView.setText("النقاط: "+score+"  |  الأفضل: "+best);}
 void gameOver(final int score){if(score>best){best=score;prefs.edit().putInt("best",best).apply();}new AlertDialog.Builder(this).setTitle("انتهى السباق").setMessage("نتيجتك: "+score+"\nأفضل نتيجة: "+best).setCancelable(false).setPositiveButton("إعادة اللعب",new DialogInterface.OnClickListener(){public void onClick(DialogInterface d,int w){startRace();}}).setNegativeButton("القائمة",new DialogInterface.OnClickListener(){public void onClick(DialogInterface d,int w){showMenu();}}).show();}
 LinearLayout panel(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setGravity(Gravity.CENTER);r.setPadding(dp(24),dp(16),dp(24),dp(16));r.setBackgroundColor(0xffe1f3fb);return r;}
 TextView text(String s,int z,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(0xff153a63);v.setGravity(Gravity.CENTER);v.setPadding(dp(5),dp(8),dp(5),dp(8));v.setTypeface(Typeface.DEFAULT,bold?Typeface.BOLD:Typeface.NORMAL);return v;}
 Button button(String s,int c){Button b=new Button(this);b.setText(s);b.setTextSize(16);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);GradientDrawable d=new GradientDrawable();d.setColor(c);d.setCornerRadius(dp(12));b.setBackground(d);return b;}
 int dp(int x){return(int)(x*getResources().getDisplayMetrics().density+.5f);}
 public void onBackPressed(){if(race!=null&&race.running){race.stop();race=null;showMenu();}else super.onBackPressed();}

 final class RaceView extends View{
  Paint p=new Paint(3);Handler h=new Handler();Random rnd=new Random();boolean running,paused,demo;int lane=1,enemyLane=0,score;float enemyY=-100,roadOffset,speed=7;
  Runnable tick=new Runnable(){public void run(){if(!running)return;if(!paused){enemyY+=speed;roadOffset=(roadOffset+speed)%100;if(enemyY>getHeight()){enemyY=-dp(80);enemyLane=rnd.nextInt(3);score++;speed=Math.min(18,7+score*.22f);updateScore(score);}float carY=getHeight()-dp(135);if(enemyLane==lane&&enemyY+dp(75)>carY&&enemyY<carY+dp(90)){running=false;invalidate();gameOver(score);return;}invalidate();}h.postDelayed(this,32);}};
  RaceView(Context c){super(c);p.setAntiAlias(true);}
  void start(){running=true;paused=false;enemyLane=rnd.nextInt(3);enemyY=-dp(100);h.post(tick);}
  void stop(){running=false;h.removeCallbacksAndMessages(null);}
  void togglePause(){paused=!paused;}
  void move(int delta){if(!paused&&running)lane=Math.max(0,Math.min(2,lane+delta));invalidate();}
  protected void onDraw(Canvas c){float w=getWidth(),hh=getHeight();p.setStyle(Paint.Style.FILL);p.setColor(0xff68b85e);c.drawRect(0,0,w,hh,p);float roadL=w*.18f,roadR=w*.82f;p.setColor(0xff555b62);c.drawRect(roadL,0,roadR,hh,p);p.setColor(Color.WHITE);c.drawRect(roadL,0,roadL+dp(5),hh,p);c.drawRect(roadR-dp(5),0,roadR,hh,p);float laneW=(roadR-roadL)/3f;p.setColor(0xffffe45c);for(int k=1;k<3;k++)for(float y=-100+roadOffset;y<hh;y+=100)c.drawRect(roadL+k*laneW-dp(2),y,roadL+k*laneW+dp(2),y+dp(48),p);if(demo){drawCar(c,roadL+laneW*1.5f,hh*.6f,0xffe53935);return;}drawCar(c,roadL+laneW*(lane+.5f),hh-dp(120),0xff1687c3);drawCar(c,roadL+laneW*(enemyLane+.5f),enemyY,0xffe53935);if(paused){p.setColor(0xaa000000);c.drawRect(0,0,w,hh,p);label(c,"متوقف مؤقتًا",w*.5f,hh*.5f,dp(28));}}
  void drawCar(Canvas c,float x,float y,int color){float cw=dp(54),ch=dp(88);p.setColor(0xff20252a);c.drawRoundRect(new RectF(x-cw*.58f,y+ch*.16f,x+cw*.58f,y+ch*.84f),dp(8),dp(8),p);p.setColor(color);c.drawRoundRect(new RectF(x-cw*.48f,y,x+cw*.48f,y+ch),dp(12),dp(12),p);p.setColor(0xffc9efff);c.drawRoundRect(new RectF(x-cw*.32f,y+ch*.16f,x+cw*.32f,y+ch*.42f),dp(6),dp(6),p);p.setColor(0xffffe082);c.drawCircle(x-cw*.3f,y+ch*.85f,dp(5),p);c.drawCircle(x+cw*.3f,y+ch*.85f,dp(5),p);}
  void label(Canvas c,String s,float x,float y,float z){p.setColor(Color.WHITE);p.setTextAlign(Paint.Align.CENTER);p.setTextSize(z);p.setFakeBoldText(true);c.drawText(s,x,y,p);p.setFakeBoldText(false);}
  protected void onDetachedFromWindow(){stop();super.onDetachedFromWindow();}
 }
}
