name: retro_games_ar
description: منصة ألعاب أتاري عربية صغيرة - طائرة الوقود وطريق التحمل.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0
  shared_preferences: ^2.2.3

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/shared/
    - assets/sounds/fuel_plane/
    - assets/sounds/retro_road/
